name: .NET Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore Dependencies
        run: dotnet restore API.sln

      - name: Build Solution
        run: dotnet build API.sln --configuration Debug --no-restore

      - name: Run Tests with Coverage
        run: dotnet test Tests/API.Tests/API.Tests.csproj --no-build --verbosity normal --collect:"XPlat Code Coverage"

      - name: Generate Coverage Report
        uses: danielpalme/ReportGenerator-GitHub-Action@5.2.0
        with:
          reports: "Tests/API.Tests/TestResults/**/coverage.cobertura.xml"
          targetdir: "coveragereport"
          reporttypes: "HtmlInline;Cobertura"

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: CoverageReport
          path: coveragereport
