name: .NET Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Verify Files Exist (Debugging)
        run: ls -R

      - name: Check Current Directory (Debugging)
        run: pwd && ls -l

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore Dependencies
        run: dotnet restore API.sln

      - name: Build Solution
        run: dotnet build API.sln --configuration Debug --no-restore
